# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: branch main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_and_build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up JDK 1.15
      uses: actions/setup-java@v1
      with:
        java-version: 1.15

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew test

    - name: Build project
      run: ./gradlew clean build -x test
